# Generated by Django 4.2.5 on 2025-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_detection', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetection',
            name='license_plate_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
